<Project Sdk="Godot.NET.Sdk/4.2.2-moonskrive">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>11.0</LangVersion>

    <EnableDynamicLoading>true</EnableDynamicLoading>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <GodotFloat64>true</GodotFloat64>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="dec/**" />
    <Content Include="src\network\ARCHITECTURE.md" />
    <Content Include="thirdparty\.gitignore" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="thirdparty/arbor/arbor-generator/**/*" />
    <ProjectReference Include="thirdparty/arbor/arbor-generator/arbor-generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />

    <Compile Remove="thirdparty/greact/greact-generator/**/*" />
    <ProjectReference Include="thirdparty\greact\greact-generator\greact-generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />

    <Compile Remove="thirdparty/gdunit4/**/*" />
    <ProjectReference Include="thirdparty\gdunit4\testadapter\gdUnit4TestsAdapter.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" Version="0.7.4" />

    <!-- tests don't show up without this (why not?) -->
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
  </ItemGroup>

  <PropertyGroup>
    <!-- this is apparently Rider-specific -->
    <RunSettingsFilePath>$(MSBuildProjectDirectory)/moonskrive.runsettings</RunSettingsFilePath>
  </PropertyGroup>
</Project>