<Project Sdk="Godot.NET.Sdk/4.2.1-moonskrive">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <GodotFloat64>true</GodotFloat64>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="dec/**" />
    <Content Include="src\network\ARCHITECTURE.md" />
    <Content Include="thirdparty\.gitignore" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="thirdparty/arbor/generator/**/*" />
    <ProjectReference Include="thirdparty/arbor/generator/generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ZstdSharp.Port" Version="0.7.4" />
  </ItemGroup>
</Project>