<Project Sdk="Godot.NET.Sdk/4.4.1-nutdealer">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>13</LangVersion>

    <EnableDynamicLoading>true</EnableDynamicLoading>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <GodotFloat64>true</GodotFloat64>

    <!-- "member" hides "other member" -->
    <WarningsAsErrors>CS0108</WarningsAsErrors>
    <Configurations>Debug;Optimize;StrippedDebug;StrippedOptimize;Export;StrippedExport</Configurations>
    <Platforms>AnyCPU</Platforms>

    <!-- even in release, we'll want these for crashlogs -->
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="test/**/*" />
  </ItemGroup>

  <ItemGroup Condition="$(Configuration.Contains('Stripped')) Or $(Configuration.Contains('Export'))">
    <Compile Remove="**/COPYRIGHT_INFRINGEMENT/**/*" />
  </ItemGroup>
  
  <PropertyGroup Condition="$(Configuration.Contains('Stripped'))">
    <!-- this doesn't need to be included in Export because Export also doesn't package the files themselves -->
    <DefineConstants>$(DefineConstants);STRIPPED</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration.Contains('Optimize')) Or $(Configuration.Contains('Export'))">
    <Optimize>true</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration.Contains('Export'))">
    <DefineConstants>$(DefineConstants);EXPORT</DefineConstants>
  </PropertyGroup>

  <!-- this bit of harness is required to make the debug/optimized/release stuff work -->
  <Target Name="SaveBuildOutputPath" AfterTargets="Build">
    <PropertyGroup>
      <OutputPathInfoFile>$(MSBuildProjectDirectory)\.godot\mono\temp\LastBuild.txt</OutputPathInfoFile>
    </PropertyGroup>

    <WriteLinesToFile File="$(OutputPathInfoFile)"
                      Lines="$(Configuration)"
                      Overwrite="true" />

    <Message Text="Build configuration `$(Configuration)` saved to: $(OutputPathInfoFile)" Importance="high" />
  </Target>
</Project>
