[tool.poetry]
name = "tools"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"
psutil = "*"

# needed for the build system
scons = "*"
requests = "^2.31.0"
gitpython = "^3.1.44"
pathspec = "^0.12.1"
beautifulsoup4 = "^4.13.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
